Repository helmholtz-analytics/heat, pull requests merged in 2020-04, with the labels that each got.

#515 Features/514 var std numpylike
  CHANGELOG.md
  heat/core/dndarray.py
  heat/core/statistics.py
  heat/core/tests/test_indexing.py
  heat/core/tests/test_statistics.py
Labels: enhancement

#519 Bug/490 gnb testing
  CHANGELOG.md
  heat/core/dndarray.py
  heat/core/indexing.py
  heat/naive_bayes/tests/test_gaussiannb.py
Labels: bug :bug:, testing

#535 Introduction of BaseEstimator and mixins for high-level analysis algorithms
  CHANGELOG.md
  heat/__init__.py
  heat/cluster/kmeans.py
  heat/cluster/spectral.py
  heat/cluster/tests/test_kmeans.py
  heat/cluster/tests/test_spectral.py
  heat/core/__init__.py
  heat/core/base.py
  heat/naive_bayes/gaussianNB.py
  heat/naive_bayes/tests/test_gaussiannb.py
  heat/regression/__init__.py
  heat/regression/lasso.py
  heat/regression/lasso/__init__.py
  heat/regression/lasso/lasso.py
  heat/regression/lasso/tests/test_lasso.py
  heat/regression/tests/__init__.py
  heat/regression/tests/test_lasso.py
  heat/utils/matrixgallery.py
Labels: API, enhancement
