Repository helmholtz-analytics/heat, pull requests merged in 2021-06, with the labels that each got.

#758 Fix indexing inconsistencies
  CHANGELOG.md
  heat/core/_operations.py
  heat/core/dndarray.py
  heat/core/linalg/basics.py
  heat/core/linalg/solver.py
  heat/core/linalg/tests/test_qr.py
  heat/core/tests/test_dndarray.py
  heat/core/tests/test_manipulations.py
  heat/core/tests/test_printing.py
  heat/naive_bayes/gaussianNB.py
  heat/naive_bayes/tests/test_gaussiannb.py
Labels: bug :bug:

#791 docs copybutton
  doc/source/conf.py
  doc/source/tutorial_30_minutes.rst
  doc/source/tutorials.rst
Labels: documentation :book:

#787 IO import issues
  CHANGELOG.md
  heat/classification/tests/test_knn.py
  heat/core/io.py
  heat/core/tests/test_io.py
  heat/utils/data/tests/test_partial_dataset.py
Labels: bug :bug:

#809 add inverse hyperbolic functions
  CHANGELOG.md
  heat/core/tests/test_trigonometrics.py
  heat/core/trigonometrics.py
Labels: API

#821 Bug/808 clustering tutorial
  CHANGELOG.md
  doc/source/tutorial_clustering.rst
  heat/core/dndarray.py
  heat/core/manipulations.py
  heat/core/tests/test_dndarray.py
Labels: bug :bug:, enhancement

#796 Bug/795-reshape split none to new split
  CHANGELOG.md
  heat/core/manipulations.py
  heat/core/tests/test_dndarray.py
  heat/core/tests/test_manipulations.py
Labels: API, bug :bug:, enhancement

#794 meshgrid implementation
  CHANGELOG.md
  heat/core/factories.py
  heat/core/tests/test_factories.py
Labels: API, enhancement
