Repository helmholtz-analytics/heat, pull requests merged in 2021-02, with the labels that each got.

#717 Enhancement/jenkins
  .github/workflows/pre-commit.yml
  .travis.yml
  CHANGELOG.md
  Jenkinsfile
  README.md
Labels: organizational, testing

#711 implement isfinite isinf isnan
  CHANGELOG.md
  heat/core/logical.py
  heat/core/tests/test_logical.py
Labels: enhancement, local operator

#724 test on multiple processors
  Jenkinsfile
Labels: testing

#660 Features/584 data parallel
  .gitignore
  CHANGELOG.md
  codecov.yml
  examples/nn/imagenet.py
  examples/nn/mnist.py
  heat/__init__.py
  heat/classification/tests/test_knn.py
  heat/cluster/tests/test_kmeans.py
  heat/cluster/tests/test_kmedians.py
  heat/cluster/tests/test_kmedoids.py
  heat/cluster/tests/test_spectral.py
  heat/core/tests/test_dndarray.py
  heat/core/tests/test_io.py
  heat/core/tests/test_statistics.py
  heat/datasets/diabetes.h5
  heat/datasets/iris.csv
  heat/datasets/iris.h5
  heat/datasets/iris.nc
  heat/datasets/iris_X_test.csv
  heat/datasets/iris_X_train.csv
  heat/datasets/iris_labels.csv
  heat/datasets/iris_y_pred_proba.csv
  heat/datasets/iris_y_test.csv
  heat/datasets/iris_y_train.csv
  heat/naive_bayes/tests/test_gaussiannb.py
  heat/nn/__init__.py
  heat/nn/data_parallel.py
  heat/nn/functional.py
  heat/nn/tests/__init__.py
  heat/nn/tests/test_data_parallel.py
  heat/nn/tests/test_nn.py
  heat/optim/__init__.py
  heat/optim/dp_optimizer.py
  heat/optim/lr_scheduler.py
  heat/optim/tests/__init__.py
  heat/optim/tests/test_optim.py
  heat/regression/tests/test_lasso.py
  heat/utils/__init__.py
  heat/utils/data/__init__.py
  heat/utils/data/_utils.py
  heat/utils/data/datatools.py
  heat/utils/data/matrixgallery.py
  heat/utils/data/mnist.py
  heat/utils/data/partial_dataset.py
  heat/utils/data/tests/__init__.py
  heat/utils/data/tests/test_matrixgallery.py
  heat/utils/data/tests/test_partial_dataset.py
  heat/utils/tests/__init__.py
  heat/utils/tests/test_vision_transforms.py
  heat/utils/vision_transforms.py
  setup.py
Labels: testing
