Repository helmholtz-analytics/heat, pull requests merged in 2022-04, with the labels that each got.

#928 add digitize/bucketize
  CHANGELOG.md
  heat/core/statistics.py
  heat/core/tests/test_statistics.py
Labels: PR talk

#948 Improve save_csv string formatting
  CHANGELOG.md
  heat/core/io.py
  heat/core/tests/test_io.py
Labels: PR talk, merge

#960 Random: Replaced factories.array with DNDarray
  CHANGELOG.md
  heat/core/random.py
Labels: PR talk, merge

#967 Duplicate MPI_SELF as well
  CHANGELOG.md
  heat/core/communication.py
Labels: merge

#595 Features/30 convolve
  CHANGELOG.md
  heat/core/__init__.py
  heat/core/dndarray.py
  heat/core/manipulations.py
  heat/core/signal.py
  heat/core/tests/test_dndarray.py
  heat/core/tests/test_manipulations.py
  heat/core/tests/test_signal.py
Labels: PR talk, merge

#945 Add `out` and `where` args for `ht.div`
  CHANGELOG.md
  heat/core/_operations.py
  heat/core/arithmetics.py
  heat/core/tests/test_arithmetics.py
Labels: PR talk, merge
