Repository helmholtz-analytics/heat, pull requests merged in 2023-08, with the labels that each got.

#1187 Create configuration file for Read the Docs
  .readthedocs.yaml
Labels: documentation :book:

#1188 Merge latest 1.3.x updates into `main`
  .readthedocs.yaml
Labels: documentation :book:

#1190 Small fixes to automated branch creation on Issue assignment
  .github/issue-branch.yml
  quick_start.md
Labels: documentation :book:, workflows

#1192 Reorganize badges order and labels on repo landing page
  README.md
Labels: documentation

#1151 Migrated bechmarks to gitlab
  .github/workflows/bench_report.yml
  .github/workflows/bench_trigger.yml
  .github/workflows/benchmark_main.yml
  .github/workflows/benchmark_pr.yml
Labels: benchmark PR, merge queue

#1193 Repository docs update
  .github/ISSUE_TEMPLATE/bug_report.yml
  contributing.md
  quick_start.md
Labels: documentation

#1195 Fixed grammatical mistakes in few markdown files.
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  README.md
  RELEASE.md
  contributing.md
  docker/README.md
  quick_start.md
Labels: documentation, merge queue

#1089 Speed up array declaration when possible in `io`module
  heat/core/io.py
Labels: chore, merge queue

#1086 Add `hermitian()` to matrix gallery
  heat/utils/data/matrixgallery.py
Labels: linalg

#1005 Reduction operations on entire array now return 0-dimensional `DNDarray`
  heat/core/_operations.py
  heat/core/sanitation.py
  heat/core/tests/test_arithmetics.py
  heat/core/tests/test_logical.py
  heat/core/tests/test_sanitation.py
  heat/core/tests/test_statistics.py
  heat/core/tests/test_suites/basic_test.py
  heat/naive_bayes/tests/test_gaussiannb.py
Labels: bug, reduction operators, GSoC, array API, merge queue

#1200 Remove restriction to < 7 processes in `test_spectral.py`
  heat/cluster/tests/test_spectral.py
Labels: testing, merge queue

#1202 Separate data and computation in benchmarks
  .perun.ini
  benchmarks/cb/cluster.py
  benchmarks/cb/linalg.py
  benchmarks/cb/main.py
  benchmarks/cb/manipulations.py
Labels: benchmarking, PR talk, benchmark PR, merge queue
