Repository helmholtz-analytics/heat, pull requests merged in 2023-11, with the labels that each got.

#1191 Binary special methods return NotImplemented
  heat/core/_operations.py
  heat/core/arithmetics.py
  heat/core/linalg/basics.py
  heat/core/linalg/tests/test_basics.py
  heat/core/tests/test_arithmetics.py
  heat/core/tests/test_dndarray.py
Labels: PR talk, arithmetics, merge queue

#1178 Split release and source dockerfile
  .github/workflows/docker.yml
  docker/Dockerfile
  docker/Dockerfile.release
  docker/Dockerfile.source
  docker/README.md
  docker/scripts/build_and_push.sh
  docker/scripts/install_print_test.sh
  docker/scripts/test_nvidia_image_haicore_enroot.sh
  docker/singularity-dockerfile.sample
  quick_start.md
Labels: documentation, PR talk, interoperability

#1264 Fix Pytorch release tracking workflows
  .github/workflows/pytorch-latest-main.yml
  .github/workflows/pytorch-latest-release.yml
  heat/core/linalg/tests/test_solver.py
Labels: workflows

#1257 Docker release 1.3.x update
  .github/workflows/docker.yml
  docker/Dockerfile
  docker/Dockerfile.release
  docker/Dockerfile.source
  docker/README.md
  docker/scripts/build_and_push.sh
  docker/scripts/install_print_test.sh
  docker/scripts/test_nvidia_image_haicore_enroot.sh
  docker/singularity-dockerfile.sample
  quick_start.md
Labels: documentation, PR talk, interoperability, merge queue

#1268 Merge latest `release/1.3.x` changes and upgrade version in `main`
  .github/workflows/pytorch-latest-main.yml
  .github/workflows/pytorch-latest-release.yml
  heat/core/linalg/tests/test_solver.py
  heat/core/version.py
Labels: workflows, CI

#1266 Sync `pre-commit` configuration with `main` branch
  .pre-commit-config.yaml
Labels: workflows

#1259 Bug-fix for lasso on GPU
  heat/regression/lasso.py
Labels: bug, PR talk, merge queue

#1201 Fix `ht.diff` for 1-element-axis edge case
  heat/core/arithmetics.py
  heat/core/tests/test_arithmetics.py
Labels: bug, indexing, arithmetics

#1274 Update version before release
  heat/core/version.py
Labels: chore

#1278 Merge release v1.3.1 into `main`
  CHANGELOG.md
  heat/core/arithmetics.py
  heat/core/tests/test_arithmetics.py
Labels: chore

#1218 Distributed Fast Fourier Transforms
  heat/__init__.py
  heat/core/stride_tricks.py
  heat/core/tests/test_suites/basic_test.py
  heat/fft/__init__.py
  heat/fft/fft.py
  heat/fft/tests/__init__.py
  heat/fft/tests/test_fft.py
Labels: enhancement, signal processing
