Repository helmholtz-analytics/heat, pull requests merged in 2023-04, with the labels that each got.

#1136 Fixed PyTorch version check in `sparse` module
  heat/sparse/factories.py
Labels: bug :bug:

#1008 API: Rename `keepdim` kwarg to `keepdims`
  heat/cluster/_kcluster.py
  heat/cluster/kmeans.py
  heat/cluster/kmedians.py
  heat/cluster/kmedoids.py
  heat/core/_operations.py
  heat/core/arithmetics.py
  heat/core/linalg/basics.py
  heat/core/linalg/tests/test_basics.py
  heat/core/logical.py
  heat/core/statistics.py
  heat/core/tests/test_factories.py
  heat/core/tests/test_logical.py
  heat/core/tests/test_rounding.py
  heat/core/tests/test_statistics.py
  heat/naive_bayes/gaussianNB.py
Labels: GSoC, array API

#1141 `heat.pow()` speed-up when exponent is `int`
  .gitlab-ci.yml
  heat/core/arithmetics.py
  heat/core/tests/test_arithmetics.py
Labels: bug :bug:, enhancement, benchmarking

#1137 Continous Benchmarking Action
  .github/release-drafter.yml
  .github/workflows/benchmark_main.yml
  .github/workflows/benchmark_pr.yml
  .github/workflows/pytorch-latest-main.yml
  .github/workflows/pytorch-latest-release.yml
  .gitignore
  .perun.ini
  README.md
  benchmarks/2020/__init__.py
  benchmarks/2020/distance_matrix/__init__.py
  benchmarks/2020/distance_matrix/config.json
  benchmarks/2020/distance_matrix/dask-auto-cpu.py
  benchmarks/2020/distance_matrix/dask-chunks-cpu.py
  benchmarks/2020/distance_matrix/heat-cpu.py
  benchmarks/2020/distance_matrix/heat-gpu.py
  benchmarks/2020/distance_matrix/numpy-cpu.py
  benchmarks/2020/distance_matrix/torch-cpu.py
  benchmarks/2020/distance_matrix/torch-gpu.py
  benchmarks/2020/generate_jobscripts.py
  benchmarks/2020/kmeans/__init__.py
  benchmarks/2020/kmeans/config.json
  benchmarks/2020/kmeans/dask-auto-cpu.py
  benchmarks/2020/kmeans/dask-chunks-cpu.py
  benchmarks/2020/kmeans/heat-cpu.py
  benchmarks/2020/kmeans/heat-gpu.py
  benchmarks/2020/kmeans/numpy-cpu.py
  benchmarks/2020/kmeans/torch-cpu.py
  benchmarks/2020/kmeans/torch-gpu.py
  benchmarks/2020/lasso/__init__.py
  benchmarks/2020/lasso/config.json
  benchmarks/2020/lasso/dask-auto-cpu.py
  benchmarks/2020/lasso/dask-chunks-cpu.py
  benchmarks/2020/lasso/heat-cpu.py
  benchmarks/2020/lasso/heat-gpu.py
  benchmarks/2020/lasso/numpy-cpu.py
  benchmarks/2020/lasso/torch-cpu.py
  benchmarks/2020/lasso/torch-gpu.py
  benchmarks/2020/statistical_moments/__init__.py
  benchmarks/2020/statistical_moments/config.json
  benchmarks/2020/statistical_moments/dask-auto-cpu.py
  benchmarks/2020/statistical_moments/dask-chunks-cpu.py
  benchmarks/2020/statistical_moments/heat-cpu.py
  benchmarks/2020/statistical_moments/heat-gpu.py
  benchmarks/2020/statistical_moments/numpy-cpu.py
  benchmarks/2020/statistical_moments/torch-cpu.py
  benchmarks/2020/statistical_moments/torch-gpu.py
  benchmarks/cb/cluster.py
  benchmarks/cb/linalg.py
  benchmarks/cb/main.py
  benchmarks/cb/manipulations.py
  heat/cluster/tests/test_kmeans.py
  heat/cluster/tests/test_kmedians.py
  heat/cluster/tests/test_kmedoids.py
  heat/utils/data/__init__.py
  heat/utils/data/spherical.py
  setup.py
Labels: benchmarking, workflows, benchmark PR
