Repository helmholtz-analytics/heat, pull requests merged in 2023-06, with the labels that each got.

#1126 hSVD (rank and tolerance, new)
  benchmarks/cb/linalg.py
  heat/core/linalg/__init__.py
  heat/core/linalg/svd.py
  heat/core/linalg/svdtools.py
  heat/core/linalg/tests/test_svdtools.py
  heat/utils/data/matrixgallery.py
  heat/utils/data/tests/test_matrixgallery.py
  heat/utils/data/tests/test_partial_dataset.py
Labels: enhancement, high-level functions, linalg

#1020 Implement `broadcast_arrays`, `broadcast_to`
  heat/core/manipulations.py
  heat/core/sanitation.py
  heat/core/tests/test_arithmetics.py
  heat/core/tests/test_manipulations.py
  heat/core/tests/test_operations.py
  heat/core/tests/test_statistics.py
Labels: enhancement, GSoC, array API

#1119 `ht.array()` default to `copy=None` (e.g., only if necessary)
  heat/core/factories.py
  heat/core/manipulations.py
  heat/core/memory.py
  heat/core/tests/test_factories.py
  heat/core/tests/test_operations.py
  heat/core/types.py
Labels: factories, array API, memory footprint, benchmark PR

#1167 Update version on `main` after releasing v1.3.0
  heat/core/version.py
Labels: documentation :book:

#1166 Documentation: Release HowTo
  RELEASE.md
Labels: documentation :book:
