Repository helmholtz-analytics/heat, pull requests merged in 2023-02, with the labels that each got.

#788 Interface for DPPY interoperability
  CHANGELOG.md
  heat/core/dndarray.py
  heat/core/factories.py
  heat/core/tests/test_dndarray.py
  heat/core/tests/test_factories.py
Labels: interoperability

#1094 Fix division precision error in `random` module
  heat/core/random.py
  heat/core/tests/test_random.py
Labels: bug :bug:, random

#1103 Work-around for pre-commit ci failure
  heat/nn/data_parallel.py
Labels: bug :bug:

#1095 Fix #1085: Convolve with distributed kernel on multiple GPUs
  heat/core/signal.py
Labels: bug :bug:
