Repository helmholtz-analytics/heat, pull requests merged in 2023-01, with the labels that each got.

#1063 add __eq__ to Device
  heat/core/devices.py
  heat/core/tests/test_devices.py
Labels: enhancement

#983 Signal processing: fully distributed 1D convolution
  heat/core/signal.py
  heat/core/tests/test_signal.py
Labels: enhancement, GSoC, signal processing

#1037 Distributed weighted `average()` along tuple of axes: shape of `weights` to match shape of input
  heat/core/statistics.py
  heat/core/tests/test_statistics.py
Labels: documentation :book:, API, GSoC
