Repository helmholtz-analytics/heat, pull requests merged in 2023-10, with the labels that each got.

#1220 Trigger Benchmark Corrections
  .github/workflows/bench_report.yml
  .github/workflows/bench_trigger.yml
Labels: benchmark PR

#1227 Benchmarks: missing branch argument in gitlab pipeline trigger
  .github/workflows/bench_trigger.yml
Labels: bug, benchmarking, CI, merge queue

#1234 Update sphinx package requirements
  doc/requirements.txt
Labels: documentation, merge queue

#1211 Updated `.pre-commit-config.yaml` file and reformatted few files for better readability.
  .pre-commit-config.yaml
  benchmarks/2020/distance_matrix/dask-chunks-cpu.py
  benchmarks/2020/generate_jobscripts.py
  examples/nn/imagenet-DASO.py
  examples/nn/imagenet.py
  heat/cluster/_kcluster.py
  heat/core/base.py
  heat/core/factories.py
  heat/core/io.py
  heat/core/linalg/svdtools.py
  heat/core/manipulations.py
  heat/core/sanitation.py
  heat/core/statistics.py
  heat/utils/data/matrixgallery.py
Labels: workflows, CI, merge queue

#1230 Remove calls to deprecated `Tensor.storage()` when using newer PyTorch versions
  heat/core/communication.py
  heat/core/dndarray.py
  heat/core/factories.py
  heat/core/manipulations.py
  heat/core/memory.py
  heat/core/tests/test_dndarray.py
  heat/optim/dp_optimizer.py
  heat/optim/tests/test_dp_optimizer.py
  heat/preprocessing/tests/test_preprocessing.py
Labels: bug, types, interoperability, To be discussed, merge queue

#1245 Update `sphinx` package requirements on `main`
  doc/requirements.txt
Labels: documentation, PR talk, merge queue

#1238 Update Heat Tutorials, fix typos.
  doc/source/getting_started.rst
  doc/source/tutorial_clustering.rst
  doc/source/tutorial_parallel_computation.rst
Labels: documentation, PR talk, merge queue

#1247 Continuous Benchmarking for the Preprocessing Module
  benchmarks/cb/main.py
  benchmarks/cb/preprocessing.py
Labels: enhancement, benchmarking, PR talk, benchmark PR, CI, merge queue
