Repository helmholtz-analytics/heat, pull requests merged in 2024-12, with the labels that each got.

#1720 Support batched QR decomposition
  heat/core/linalg/qr.py
  heat/core/linalg/tests/test_qr.py
Labels: enhancement, linalg, merge queue, ESAPCA

#1639 Features/1563 Add Dynamic Mode Decomposition (DMD)
  heat/core/linalg/svdtools.py
  heat/core/random.py
  heat/core/tests/test_random.py
  heat/decomposition/__init__.py
  heat/decomposition/dmd.py
  heat/decomposition/tests/test_dmd.py
Labels: high-level functions, ESAPCA

#1731 Modernise setup.py configuration
  pyproject.toml
  setup.cfg
Labels: chore, backport release/1.5.x

#1741 make it easier to get to GitHub from the docs
  doc/source/index.rst
Labels: documentation, backport release/1.5.x

#1748 Linters will no longer format tutorials
  .pre-commit-config.yaml
Labels: workflows, backport release/1.5.x

#1527 Features/HPC-tutorial via python script
  tutorials/hpc/01_basics/01_basics_dndarrays.py
  tutorials/hpc/01_basics/02_basics_datatypes.py
  tutorials/hpc/01_basics/03_basics_operations.py
  tutorials/hpc/01_basics/04_basics_indexing.py
  tutorials/hpc/01_basics/05_basics_broadcast.py
  tutorials/hpc/01_basics/06_basics_gpu.py
  tutorials/hpc/01_basics/07_basics_distributed.py
  tutorials/hpc/01_basics/08_basics_distributed_operations.py
  tutorials/hpc/01_basics/09_basics_distributed_matmul.py
  tutorials/hpc/01_basics/10_interoperability.py
  tutorials/hpc/01_basics/11_internals_1.py
  tutorials/hpc/01_basics/12_internals_2.py
  tutorials/hpc/02_loading_preprocessing/01_IO.py
  tutorials/hpc/02_loading_preprocessing/02_preprocessing.py
  tutorials/hpc/02_loading_preprocessing/iris.csv
  tutorials/hpc/03_matrix_factorizations/matrix_factorizations.py
  tutorials/hpc/04_clustering/clustering.py
  tutorials/hpc/05_your_turn/now_its_your_turn.py
  tutorials/hpc/2_basics.ipynb
  tutorials/hpc/3_internals.ipynb
  tutorials/hpc/4_loading_preprocessing.ipynb
  tutorials/hpc/5_matrix_factorizations.ipynb
  tutorials/hpc/6_clustering.ipynb
  tutorials/hpc/README.md
  tutorials/hpc/slurm_script_cpu.sh
  tutorials/hpc/slurm_script_gpu.sh
  tutorials/hpc_notebooks/1_intro.ipynb
  tutorials/hpc_notebooks/2_basics.ipynb
  tutorials/hpc_notebooks/3_internals.ipynb
  tutorials/hpc_notebooks/4_loading_preprocessing.ipynb
  tutorials/hpc_notebooks/5_matrix_factorizations.ipynb
  tutorials/hpc_notebooks/6_clustering.ipynb
Labels: documentation

#1681 Release drafter update and autolabeler
  .github/rd-release-config.yml
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release-prep.yml
Labels: workflows

#1678 Release drafter fix and autolabeling (for release)
  .github/rd-release-config.yml
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release-prep.yml
Labels: workflows
