Repository helmholtz-analytics/heat, pull requests merged in 2024-07, with the labels that each got.

#1420 Implement sketched percentile
  heat/core/statistics.py
  heat/core/tests/test_statistics.py
  heat/preprocessing/preprocessing.py
  heat/preprocessing/tests/test_preprocessing.py
Labels: statistics, merge queue

#1515 Support batch 1-d convolution in `ht.signal.convolve`
  heat/core/signal.py
  heat/core/tests/test_signal.py
Labels: signal

#1388 Load functionality for multiple .npy files
  heat/core/io.py
  heat/core/tests/test_io.py
Labels: I/O

#1516 Distributed `vmap` functionality for vectorization across split dimension
  heat/core/__init__.py
  heat/core/tests/test_vmap.py
  heat/core/vmap.py
Labels: enhancement, merge queue

#1502 Add decomposition module and PCA-interface
  heat/decomposition/__init__.py
  heat/decomposition/pca.py
  heat/decomposition/tests/__init__.py
  heat/decomposition/tests/test_pca.py
Labels: enhancement, high-level functions, ESAPCA

#1569 Update CHANGELOG.md to v1.4.2
  CHANGELOG.md
Labels: documentation

#1573 Drop Python 3.8, Drop PyTorch < 2, Add Python 3.12
  .github/workflows/ci.yaml
  setup.py
Labels: version, interoperability, CI, dependencies

#1576 Use python 3.9 in initial test run
  .github/workflows/ReceivePR.yml
Labels: CI

#1508 Features/1448 Refactor random module
  heat/cluster/_kcluster.py
  heat/cluster/kmeans.py
  heat/cluster/kmedians.py
  heat/cluster/kmedoids.py
  heat/core/linalg/tests/test_basics.py
  heat/core/linalg/tests/test_svdtools.py
  heat/core/random.py
  heat/core/tests/test_manipulations.py
  heat/core/tests/test_random.py
  heat/fft/tests/test_fft.py
Labels: enhancement, random, ESAPCA
