Repository helmholtz-analytics/heat, pull requests merged in 2024-10, with the labels that each got.

#1646 Raise Error for batched vector inputs on matmul
  heat/core/linalg/basics.py
  heat/core/linalg/tests/test_basics.py
Labels: bug, linalg

#1660 Release drafter action handles multi-branch releases
  .github/release-drafter.yml
Labels: workflows, CI, github_actions

#1672 fix: missing backported pr
  .github/release-drafter.yml
Labels: PR talk, chore, CI, merge queue

#1677 Refactor `test_random` to minimize collective calls
  heat/core/statistics.py
  heat/core/tests/test_random.py
  heat/utils/data/matrixgallery.py
Labels: bug, MPI, testing, HW:ROCm, backport release/1.5.x

#1561 Distributed randomized SVD
  heat/core/linalg/svdtools.py
  heat/core/linalg/tests/test_svdtools.py
  heat/core/random.py
  heat/core/types.py
  heat/decomposition/pca.py
  heat/decomposition/tests/test_pca.py
Labels: high-level functions, linalg, benchmark PR, ESAPCA

#1679 Update tutorials instructions for `ipcluster` initialization
  tutorials/local/1_intro.ipynb
Labels: bug, documentation, merge queue, backport release/1.5.x

#1687 Support PyTorch 2.4.1 (#1655)
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/ci.yaml
  heat/core/tests/test_random.py
  setup.py
Labels: interoperability
