Repository helmholtz-analytics/heat, pull requests merged in 2024-01, with the labels that each got.

#1314 Merge latest bug fixes from `release/1.3.x` into `main`
  .github/workflows/ci.yaml
  .github/workflows/latest-pytorch-support.yml
  .github/workflows/pytorch-latest-main.yml
  .github/workflows/pytorch-latest-release.yml
  heat/fft/fft.py
  heat/fft/tests/test_fft.py
Labels: chore, merge queue

#1315 Fix some NumPy deprecations in the core tests.
  heat/core/tests/test_arithmetics.py
  heat/core/tests/test_factories.py
  heat/core/tests/test_statistics.py
Labels: interoperability, merge queue

#1331 Bugs/1330 bug continuous benchmarks fail for qr due to deprecated value for tiles per proc
  benchmarks/cb/linalg.py
  heat/core/linalg/qr.py
  heat/core/linalg/tests/test_qr.py
Labels: benchmark PR
